### ISSUE TITLE
Provider crashes with Go error

### ISSUE THREAD

**Issue by johanlundberg92** [denouche/terraform-provider-awx#66]
Running against a fresh install of AWX (awx-operator-2.12.1)

```
awx_organization.it_ops: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with awx_organization.it_ops,
│   on organization.tf line 1, in resource "awx_organization" "it_ops":
│    1: resource "awx_organization" "it_ops" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-awx_v0.24.3 plugin:

panic: interface conversion: interface {} is nil, not int

goroutine 57 [running]:
github.com/denouche/terraform-provider-awx/awx.resourceOrganizationsCreate({0x100c9eb08, 0x14000611e00}, 0x0?, {0x100b4a7a0?, 0x14000152100?})
        github.com/denouche/terraform-provider-awx/awx/resource_organization.go:91 +0x57c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x140000e5a40, {0x100c9eb40, 0x14000611320}, 0xd?, {0x100b4a7a0, 0x14000152100})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:778 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140000e5a40, {0x100c9eb40, 0x14000611320}, 0x1400039e8f0, 0x140000e3300, {0x100b4a7a0, 0x14000152100})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:909 +0x8a0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400036dfb0, {0x100c9eb40?, 0x14000611200?}, 0x140004aad70)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/grpc_provider.go:1072 +0xb78
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1400022b040, {0x100c9eb40?, 0x14000610810?}, 0x140002dccb0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x100c67c20?, 0x1400022b040}, {0x100c9eb40, 0x14000610810}, 0x140002dcc40, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002241e0, {0x100ca27d8, 0x14000480680}, 0x1400045ac60, 0x14000379cb0, 0x101175d18, 0x0)
        google.golang.org/grpc@v1.57.1/server.go:1358 +0xcb4
google.golang.org/grpc.(*Server).handleStream(0x140002241e0, {0x100ca27d8, 0x14000480680}, 0x1400045ac60, 0x0)
        google.golang.org/grpc@v1.57.1/server.go:1735 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.1/server.go:970 +0xb4
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.1/server.go:981 +0x174
```

**Comment by denouche** [comment]
Fixed with #77
